name: Validate pull request before putting into queue

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display info
        run: |
          pwd
          tree -a -I '.git'
          git status
      - name: Run fast CI (emulated by a short sleep)
        run: sleep 1

  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    outputs:
      helm_any_changed: ${{ steps.changed-files-yaml.outputs.helm_any_changed }}
      helm_all_changed_files: ${{ steps.changed-files-yaml.outputs.helm_all_changed_files }}
      build_any_changed: ${{ steps.changed-files-yaml.outputs.build_any_changed }}
      build_all_changed_files: ${{ steps.changed-files-yaml.outputs.build_all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            helm:
              - '**.md'
              - helm/**.yaml
            build:
              - build.gradle.kts
          # Optionally set `files_yaml_from_source_file` to read the YAML from a file. e.g `files_yaml_from_source_file: .github/changed-files.yml`

      - name: Run step if helm file(s) change
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-yaml.outputs.helm_any_changed == 'true'
        env:
          TEST_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.helm_all_changed_files }}
        run: |
          echo "One or more helm file(s) has changed."
          echo "List all the files that have changed: $TEST_ALL_CHANGED_FILES"

      - name: Run step if build file(s) change
        if: steps.changed-files-yaml.outputs.build_any_changed == 'true'
        env:
          DOC_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.build_all_changed_files }}
        run: |
          echo "One or more build file(s) has changed."
          echo "List all the files that have changed: $DOC_ALL_CHANGED_FILES"
          

  perform-echo:
    needs:
      - changed_files
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Helm files changed"
          echo "all variables are:"
          echo "helm_any_changed: ${{ needs.changed_files.outputs.helm_any_changed }}"
          echo ${{ needs.changed_files.outputs.helm_any_changed }}
          echo "helm_all_changed_files: ${{ needs.changed_files.outputs.helm_all_changed_files }}"
          echo "build_any_changed: ${{ needs.changed_files.outputs.build_any_changed }}"
          echo ${{ needs.changed_files.outputs.build_any_changed }}
          echo "build_all_changed_files: ${{ needs.changed_files.outputs.build_all_changed_files }}"

          echo ${{ needs.changed_files.outputs.helm_any_changed == 'true' }}
          echo ${{ needs.changed_files.outputs.helm_any_changed == 'false' }}

  conditional-for-helm-change:
    needs:
      - changed_files
    runs-on: ubuntu-latest
    if: ${{ needs.changed_files.outputs.helm_any_changed == 'true' }}
    steps:
      - name: conditional-Echo
        run: |
          echo "Helm files Updated"
          cat $GITHUB_OUTPUT